export const SIGNALS = [
  {
    key: "benefit_framing",
    name: "Benefit vs. Feature Framing",
    definition:
      'Is the homepage written around the customer\'s outcome and problem ("faster time to market," "reduce your supplier risk") or is it feature/company-centric ("we offer," "our state-of-the-art facility," "about us")?',
  },
  {
    key: "bofu_cta",
    name: "Bottom-of-Funnel CTA",
    definition:
      'Is there a specific, action-oriented, bottom-of-funnel call to action ("Book a meeting," "Schedule a consultation," "Speak to an engineer," "Request a quote") or just generic, low-commitment CTAs ("Learn More," "Contact Us")?',
  },
  {
    key: "mofu_offer",
    name: "Mid-Funnel Offer",
    definition:
      "Is there a middle-of-funnel content offer for a visitor who isn't ready to talk to sales yet (download an ebook/guide/whitepaper, join a webinar, take an assessment) or nothing between the homepage and a hard sales ask?",
  },
  {
    key: "resources_section",
    name: "Resources Section",
    definition:
      "Does the site have a dedicated resources/knowledge section (guides, whitepapers, case studies, downloads) linked from navigation, or nothing of the kind?",
  },
  {
    key: "blog_currency_quality",
    name: "Blog Currency & Quality",
    definition:
      "Does the site have a current blog: posts dated in 2026, credited to a named human author (not anonymous or generic \"Admin\"), and written as real thought leadership rather than generic content that reads like it could have been generated by any AI tool with no unique point of view? All three (current, human-authored, genuine thought leadership) need to be true for a top score.",
  },
];

export const SYSTEM_PROMPT = `You are a blunt B2B content marketing analyst grading manufacturer and industrial company homepages on conversion-funnel maturity: whether the site is built to move a technical buyer from cold visitor to sales conversation.

You will be given the visible text extracted from a homepage (with its <title>), a list of navigation links that look like they point to a blog or resources section, and, if one was found and successfully fetched, the extracted text of that blog/resources page.

Grade against exactly 5 signals, each on a 1-5 integer scale where 1 means the signal is essentially absent and 5 means it is done well and specifically.

Rules:
- Base every judgment ONLY on the material provided. Do not assume a blog or resources section exists if no link was found and none was fetched — score "Blog Currency & Quality" and "Resources Section" low in that case and say so plainly in the feedback.
- If a blog page was fetched but the fetch failed, say so in the feedback for "Blog Currency & Quality" rather than guessing at its content.
- For each signal's "feedback", quote or closely paraphrase actual words from the provided text (in quotation marks) and explain in one sentence why that earns the score. Do not just restate the category definition.
- For "Blog Currency & Quality" specifically: look for visible dates on the blog page text. Treat any date in 2026 as current. Judge authorship by whether a named human byline appears (e.g. "By Jane Smith") vs. no byline or a generic one. Judge "genuine thought leadership" by whether the post titles/excerpts suggest a specific, defensible point of view (a named process, a real project, a contrarian take) vs. generic evergreen topics any company in the space could have published.
- Be specific and a little sharp. Avoid hedging language like "could potentially" or "may want to consider."
- "weakest_key" must be the key of whichever signal has the lowest score (if tied, pick the one most damaging to conversion).
- "rewrite" must be a concrete, ready-to-use fix for the weakest signal (a rewritten CTA, a specific mid-funnel offer idea, a specific headline), grounded in whatever real specifics ARE present in the material (if the text names an industry or capability anywhere, use it; otherwise write a realistic placeholder in brackets like "[your strongest case study]").
- "summary" is 1-2 plain sentences on the overall impression, no fluff.
- Respond with STRICT JSON ONLY. No markdown code fences, no preamble, no trailing commentary.

Output schema:
{
  "summary": string,
  "signals": [
    { "key": string, "score": integer 1-5, "feedback": string }
  ],
  "weakest_key": string,
  "rewrite": string
}

The "signals" array must contain exactly these 5 keys in this order: ${SIGNALS.map((s) => s.key).join(", ")}.`;

function formatLinks(links) {
  if (!links || links.length === 0) return "(none found)";
  return links.map((l) => `- "${l.text}" -> ${l.href}`).join("\n");
}

export function buildUserPrompt({ url, title, copy, blogLinks, resourceLinks, blogPage }) {
  const rubric = SIGNALS.map(
    (s, i) => `${i + 1}. ${s.name} (key: "${s.key}") — ${s.definition}`
  ).join("\n");

  let blogSection;
  if (!blogLinks || blogLinks.length === 0) {
    blogSection = "No blog/news link was found in the site's navigation or links.";
  } else if (!blogPage) {
    blogSection = `A blog-like link was found (${blogLinks[0].href}) but it was not fetched.`;
  } else if (blogPage.fetchFailed) {
    blogSection = `A blog-like link was found (${blogPage.url}) but fetching it failed.`;
  } else {
    blogSection = `Blog/news page fetched: ${blogPage.url}
Page title: ${blogPage.title || "(none found)"}
Extracted text from that page:
"""
${blogPage.copy}
"""`;
  }

  return `URL: ${url}
Page title: ${title || "(none found)"}

Grade this homepage against these 5 signals:
${rubric}

Navigation links suggestive of a blog/news section:
${formatLinks(blogLinks)}

Navigation links suggestive of a resources section:
${formatLinks(resourceLinks)}

Extracted homepage text (hero and top sections, in page order):
"""
${copy}
"""

${blogSection}

Return the JSON object now.`;
}
