export const SIGNALS = [
  {
    key: "benefit_framing",
    name: "Benefit vs. Feature Framing",
    definition:
      'Is the homepage written around the customer\'s outcome and problem ("faster time to market," "reduce your supplier risk") or is it feature/company-centric ("we offer," "our state-of-the-art facility," "about us")?',
    anchors: [
      "1 = Entirely third-person/company-centric. No outcome language anywhere (\"We are...\", \"Our facility...\").",
      "2 = Almost entirely feature/company-centric. Outcome language appears only incidentally, never as the main message.",
      "3 = Mixed. Clear outcome-focused phrases exist, but company/feature framing still dominates the primary headline and value prop.",
      "4 = Outcome-focused framing dominates most of the page. Feature/company language is supporting detail, not the lead.",
      "5 = Nearly every major heading and the primary value prop centers a specific, buyer-relevant outcome, not the company.",
    ],
  },
  {
    key: "bofu_cta",
    name: "Bottom-of-Funnel CTA",
    definition:
      'Is there a specific, action-oriented, bottom-of-funnel call to action ("Book a meeting," "Schedule a consultation," "Speak to an engineer," "Request a quote") or just generic, low-commitment CTAs ("Learn More," "Contact Us")?',
    anchors: [
      "1 = Only generic CTAs anywhere on the page (\"Contact Us\", \"Learn More\").",
      "2 = One slightly more specific CTA exists but isn't truly action/sales-ready (e.g. \"Get in Touch\").",
      "3 = At least one genuinely specific, sales-ready CTA exists (e.g. \"Request a Quote\"), but it's diluted by multiple competing low-commitment CTAs, or only appears once.",
      "4 = A specific, sales-ready CTA is prominent and repeated as the primary action across the page.",
      "5 = A specific, sales-ready CTA is the dominant, consistent primary action everywhere, with added friction reduction (scheduling link, calendar embed, live chat).",
    ],
  },
  {
    key: "mofu_offer",
    name: "Mid-Funnel Offer",
    definition:
      "Is there a middle-of-funnel content offer for a visitor who isn't ready to talk to sales yet (download an ebook/guide/whitepaper, join a webinar, take an assessment) or nothing between the homepage and a hard sales ask?",
    anchors: [
      "1 = No mid-funnel offer of any kind found anywhere in the extracted text.",
      "2 = A resource exists but functions as a reference/bottom-of-funnel link, not a captured mid-funnel offer (no download/register mechanic).",
      "3 = One genuine mid-funnel offer exists (ebook/guide/webinar/assessment) but it's buried or mentioned only once.",
      "4 = A genuine mid-funnel offer is presented prominently as a homepage option.",
      "5 = Multiple distinct mid-funnel offers are prominently presented, clearly aimed at buyers not yet ready for sales.",
    ],
  },
  {
    key: "resources_section",
    name: "Resources Section",
    definition:
      "Does the site have a dedicated resources/knowledge section (guides, whitepapers, case studies, downloads) linked from navigation, or nothing of the kind?",
    anchors: [
      "1 = No resources/knowledge link exists anywhere.",
      "2 = A resources link exists but leads to only one or two generic items (e.g. a single FAQ or spec sheet).",
      "3 = A resources section exists with a few real, specific items (a case study, a guide) but limited depth or organization.",
      "4 = A dedicated, organized resources hub exists with multiple specific, substantive items across categories.",
      "5 = A dedicated, organized resources hub with multiple categories, deep/specific content, and clear content offers (downloadable/gated assets).",
    ],
  },
  {
    key: "blog_currency_quality",
    name: "Blog Currency & Quality",
    definition:
      "Does the site have a current blog: posts dated in 2026, credited to a named human author (not anonymous or generic \"Admin\"), and written as real thought leadership rather than generic content that reads like it could have been generated by any AI tool with no unique point of view? This is three separate yes/no conditions — CURRENT (any post dated in 2026), AUTHORED (a named human byline visible), and DISTINCTIVE (titles/excerpts suggest a specific, defensible point of view, not generic evergreen topics).",
    anchors: [
      "1 = No blog/content hub exists, or it exists but has no posts dated in 2026 (stale, can't confirm current).",
      "2 = Content is current, but neither AUTHORED nor DISTINCTIVE holds (no byline, and generic evergreen topics).",
      "3 = Content is current AND exactly one of AUTHORED or DISTINCTIVE holds.",
      "4 = Content is current AND both AUTHORED and DISTINCTIVE hold, but only somewhat (e.g. byline present but point of view only mildly distinct).",
      "5 = All three hold clearly and strongly: current dated posts, a named human byline, and genuinely distinct thought leadership.",
    ],
  },
];

export const SYSTEM_PROMPT = `You are a blunt B2B content marketing analyst grading manufacturer and industrial company homepages on conversion-funnel maturity: whether the site is built to move a technical buyer from cold visitor to sales conversation.

You will be given the visible text extracted from a homepage (with its <title>), a list of navigation links that look like they point to a blog or resources section, and, if one was found and successfully fetched, the extracted text of that blog/resources page.

Grade against exactly 5 signals, each on a 1-5 integer scale. Each signal below includes anchor descriptions for every score (1-5) — use them as a decision procedure, not just inspiration. Pick the anchor that most precisely matches the evidence rather than defaulting to a middle score when unsure; the anchors are written to cover the full range of real homepages.

Rules:
- Base every judgment ONLY on the material provided. Do not assume a blog or resources section exists if no link was found and none was fetched — score "Blog Currency & Quality" and "Resources Section" using their 1-anchor in that case and say so plainly in the feedback.
- If a blog page was fetched but the fetch failed, say so in the feedback for "Blog Currency & Quality" rather than guessing at its content.
- For each signal's "feedback", quote or closely paraphrase actual words from the provided text (in quotation marks) and explain in one sentence why that specific anchor (not a neighboring one) fits. Do not just restate the category definition.
- For "Blog Currency & Quality" specifically: work through the three conditions (CURRENT, AUTHORED, DISTINCTIVE) explicitly in your own reasoning before picking a score, then state in the feedback which of the three held and which didn't. Treat any date in 2026 as current. A byline is a named human ("By Jane Smith"), not "Admin," "Team," or no name at all. DISTINCTIVE means the titles/excerpts point to something specific (a named process, a real project, a contrarian take), not a generic topic any competitor could have published.
- Be specific and a little sharp. Avoid hedging language like "could potentially" or "may want to consider."
- "weakest_key" must be the key of whichever signal has the lowest score (if tied, pick the one most damaging to conversion).
- "rewrite" must be a concrete, ready-to-use fix for the weakest signal (a rewritten CTA, a specific mid-funnel offer idea, a specific headline), grounded in whatever real specifics ARE present in the material (if the text names an industry or capability anywhere, use it; otherwise write a realistic placeholder in brackets like "[your strongest case study]").
- "summary" is 1-2 plain sentences on the overall impression, no fluff.
- Respond with STRICT JSON ONLY. No markdown code fences, no preamble, no trailing commentary.

Output schema:
{
  "summary": string,
  "signals": [
    { "key": string, "score": integer 1-5, "feedback": string }
  ],
  "weakest_key": string,
  "rewrite": string
}

The "signals" array must contain exactly these 5 keys in this order: ${SIGNALS.map((s) => s.key).join(", ")}.`;

function formatLinks(links) {
  if (!links || links.length === 0) return "(none found)";
  return links.map((l) => `- "${l.text}" -> ${l.href}`).join("\n");
}

export function buildUserPrompt({ url, title, copy, blogLinks, resourceLinks, blogPage }) {
  const rubric = SIGNALS.map((s, i) => {
    const anchorList = s.anchors.map((a) => `   - ${a}`).join("\n");
    return `${i + 1}. ${s.name} (key: "${s.key}") — ${s.definition}\n${anchorList}`;
  }).join("\n\n");

  let blogSection;
  if (!blogLinks || blogLinks.length === 0) {
    blogSection = "No blog/news link was found in the site's navigation or links.";
  } else if (!blogPage) {
    blogSection = `A blog-like link was found (${blogLinks[0].href}) but it was not fetched.`;
  } else if (blogPage.fetchFailed) {
    blogSection = `A blog-like link was found (${blogPage.url}) but fetching it failed.`;
  } else {
    blogSection = `Blog/news page fetched: ${blogPage.url}
Page title: ${blogPage.title || "(none found)"}
Extracted text from that page:
"""
${blogPage.copy}
"""`;
  }

  return `URL: ${url}
Page title: ${title || "(none found)"}

Grade this homepage against these 5 signals:
${rubric}

Navigation links suggestive of a blog/news section:
${formatLinks(blogLinks)}

Navigation links suggestive of a resources section:
${formatLinks(resourceLinks)}

Extracted homepage text (hero and top sections, in page order):
"""
${copy}
"""

${blogSection}

Return the JSON object now.`;
}
